### ISSUE TITLE
GitHub Pages now supports custom GitHub Actions workflows

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/action-build-deploy-ghpages#30]
# Overview

A blog post was [recently posted in the GitHub Changelog](https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/) regarding _(beta)_ support for custom GitHub Actions workflows directly in the repository, without having to rely upon external GitHub Actions such as this very action.

An example workflow is as shown below ([source](https://github.com/actions/starter-workflows/blob/main/pages/jekyll-gh-pages.yml)):

<details>
<summary>Expand to view example workflow</summary>

```yaml
# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```
</details>

This effectively means that there's no longer a need for such a custom GitHub Action, unless additional configuration is needed.

However, additional in-depth research is needed, such as the inputs that the [actions/jekyll-build-actions GitHub Action supports](https://github.com/actions/jekyll-build-pages/blob/main/action.yml), and whether they're sufficient enough for regular usage.

## Todos

- [ ] Experiment with the first-party GitHub Actions
- [ ] Do in-depth research on the feature-set between this action and the first-party actions
- [ ] Point new users to the first-party actions if necessary
